#! /bin/sh

### BEGIN INIT INFO
# Provides:          tweet_ip_address
# Required-Start:    $remote_fs $syslog $networking
# Required-Stop:     $remote_fs $syslog $networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting tweetIpAddress"
    # run application you want to start
    ruby /home/pi/Dev/TweetIpAddress/tweet_ip_address.rb
    ;;
  stop)
    echo "Stopping tweetIpAddress"
    ;;
  *)
    echo "Usage: /etc/init.d/tweet_ip_address {start|stop}"
    exit 1
    ;;
esac

exit 0
